# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52b8ae533f7571ff0460e2859c1400ed03e41cb1813ebc5c2ee5e5081ed1111d53a27ec0cc58aaacdff163c3311eef67250dd657456a423742aa37cdd38eae3e

test:
  secret_key_base: 4339fe41fae8d1f31fdff52b2e9a075630a29e262c81f6b810999a9de6212828e5cdf596108998f680f858107058631e34b1c237349e1327ae3cfc2c749482e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
